export const contestAbi = [
  {
    inputs: [
      { internalType: 'uint256[]', name: 'playerIds', type: 'uint256[]' },
      { internalType: 'uint256', name: 'captainId', type: 'uint256' },
      { internalType: 'uint256', name: 'viceCaptainId', type: 'uint256' },
    ],
    name: 'joinContest',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'matchId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'entryFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'deadline',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'status',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'prizePool',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'maxEntries',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'firstPrizeAmount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getEntryCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getLeaderboard',
    outputs: [
      { internalType: 'address[]', name: 'users', type: 'address[]' },
      { internalType: 'uint256[]', name: 'points', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'ranks', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'entryIndices', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'entryIndex', type: 'uint256' }],
    name: 'getTeamByEntry',
    outputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint256[]', name: 'playerIds', type: 'uint256[]' },
      { internalType: 'uint256', name: 'captainId', type: 'uint256' },
      { internalType: 'uint256', name: 'viceCaptainId', type: 'uint256' },
      { internalType: 'uint256', name: 'totalPoints', type: 'uint256' },
      { internalType: 'uint256', name: 'rank', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'entryIndex', type: 'uint256' }],
    name: 'entries',
    outputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint256[]', name: 'playerIds', type: 'uint256[]' },
      { internalType: 'uint256', name: 'captainId', type: 'uint256' },
      { internalType: 'uint256', name: 'viceCaptainId', type: 'uint256' },
      { internalType: 'uint256', name: 'totalPoints', type: 'uint256' },
      { internalType: 'uint256', name: 'rank', type: 'uint256' },
      { internalType: 'bool', name: 'claimed', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'entryIndex', type: 'uint256' }],
    name: 'claimPrize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
